# config.yaml

thresholds:
  green: 25
  orange: 60

weights:
  spf_fail: 25
  dkim_fail: 25
  dmarc_fail: 25
  brand_impersonation: 15
  reply_to_mismatch: 10     # ← neu hinzugefügt

brands:
  - paypal
  - amazon
  - google
  - apple
  - microsoft
